rem ### CHANGE ALL PATHS SO THEY POINT TO VALID DIRECTORIES ON YOUR SYSTEM  ####
set JDK_HOME=C:\Program Files\Java\jdk1.8.0_161
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_161
set CLASSPATH=%CLASSPATH%;<YOUR_PATH_TO_JARS>\Actian\PSQL-SDK-JCL-13.30.034.000\bin\psql.jar;
set CLASSPATH=%CLASSPATH%;<YOUR_PATH_TO_JARS>\Actian\PSQL-SDK-JDBC-13.30.034.000\bin\pvjdbc2.jar;
set CLASSPATH=%CLASSPATH%;<YOUR_PATH_TO_JARS>\Actian\PSQL-SDK-JDBC-13.30.034.000\bin\pvjdbc2x.jar;
set CLASSPATH=%CLASSPATH%;<YOUR_PATH_TO_JARS>\Actian\PSQL-SDK-JDBC-13.30.034.000\bin\jpscs.jar;
path=%path%;C:\Program Files\Java\jdk1.8.0_161\bin;